### PR TITLE
Refactor JSON serdes

### LINKED ISSUE #66: Current JSON (de)serialization stuff is pretty jank
and makes it a little confusing to maintain, because adding new things that need to be stored requires you to poke around in two different packages

### PR DESCRIPTION
**Pull request by zhongfu**
serialization/deserialization, ofc

hopefully we can get rid of the whole `JsonAdaptedWhatever` stuff

Add serdes for:
- [x] AddressBook
  - [x] UniquePersonList
    - [x] Person
      - [x] Name
      - [x] Email
      - [x] Address
      - [x] Phone
      - [x] Tag
      - [x] Set\<Tag\>
  - Job
    - [x] Money
    - [x] Rate

and:
- [x] rewrite load/save to use the model classes directly
- [x] get rid of JsonAdapted\*
    
closes #66

### CODE REVIEW

**Comment by zhongfu** [comment]
not implementing serializer for `Job` at the moment because it's got a `Set<Person>` which will result in duplicates when serializing the entire `AddressBook`, which can break consistency guarantees too

**Review by Spyobird — COMMENTED** [review]
Just wondering a few things:
- If the current attributes extend a superclass (for instance `Attribute<T>`), would it largely affect the nested serdes classes. (I would think due to inheritance it might not be an issue, but I am not sure)
- Adding on to that, if `Person` were to have something like an 'attribute map' to store the attributes instead of storing them by subclass (i.e. `Name`, `Address` etc.), would it result in large changes in serdes. The attribute map may function like key-value pairs and so perhaps it may have structural similarities with JSON.

I was thinking of implementing these, but if it might cause too much extra effort to work with serdes then I think it is best not to.

**Comment by zhongfu** [comment]
@Spyobird 

> * If the current attributes extend a superclass (for instance `Attribute<T>`), would it largely affect the nested serdes classes. (I would think due to inheritance it might not be an issue, but I am not sure)

should be fine -- it's possible to implement (de)serializers for generic classes, though it might be a little less straightforward

> * Adding on to that, if `Person` were to have something like an 'attribute map' to store the attributes instead of storing them by subclass (i.e. `Name`, `Address` etc.), would it result in large changes in serdes. The attribute map may function like key-value pairs and so perhaps it may have structural similarities with JSON.

don't think so, you might be able to delegate the serdes of the `Map` to Jackson and let it handle everything (as long as the type(s) of the key/value have (de)serializers implemented)

**Review by Spyobird — APPROVED** [review]
lgtm!

**Pull request merged**
